[FU-152] prototype complete
SWM-15th-ForU/freebe-frontend pull request #13
Opened 2024-08-26 11:51 UTC by eujin-shin

## 체크리스트
- [x] 불필요한 주석 처리가 없는가?

## 작업 내역
* 시연 영상을 위한 프로토타입 범위의 페이지 퍼블리싱
작가측 마이페이지, 상품관리 페이지, 의뢰자측 신청서 작성 플로우에 포함되는 페이지
* 작가측 상품 목록 조회 api, 상품 상태 변경 api 연결
* client side에서의 api 요청을 위한 베이스 코드 일부 작성
* vanilla extract에서의 디자인 시스템 구축에 따른 css 리팩토링

## 고민한 사항
* 현재 클라이언트 사이드의 api 요청은 토큰이 포함되지 않습니다. `FU-155` 티켓 처리를 통해 클라이언트 사이드 토큰 관리 로직을 추가할 예정입니다!

## 리뷰 요청사항
* 특별한 요청사항은 없습니다!
* 시급도: 높음
OAuth 수정에 따른 토큰 관리 파트 보완 이전에 리뷰 완료가 필요합니다! 🙇

## 스크린샷
<img width="772" alt="스크린샷 2024-08-26 오후 8 50 22" src="https://github.com/user-attachments/assets/6a15a0bc-bb89-40f4-9f81-8ea75bb3b016">

2024-08-26 13:11 UTC, yuseok0215 requested changes
PR에서 개발한 페이지를 봤는데 너무 잘 만들어줘서 앞으로 서비스 UI가 더 기대가 돼!!ㅎㅎ 고생했어👍
일단 프론트 개발하는 걸 혼자 진행하기로 결정(?)됐는데 조금이라도 고민이 되거나 어려운 부분 공유해주면 같이 고민해서 빠르게 해결하고 다음 테스크로 넘어갈 수 있게 많이 도와줄게!😊 화이팅🔥🔥🔥

2024-08-26 13:11 UTC, yuseok0215 commented on src/services/client/core/index.ts
> +  }
리프레쉬 토큰이 없을 때 에러를 던지는 것 같은데 혹시 이 때 사용자에게 알림을 보내거나 특정 페이지로 리디렉션하는 처리가 없어도 괜찮은지 궁금해!🤔 (따로 에러핸들링을 담당하는 부분이 있을 수 있는데 내가 모르는 걸수도 있어...ㅎㅎ)

2024-08-26 13:11 UTC, yuseok0215 commented on src/services/client/core/index.ts
> +const clientApi = ky.create({ prefixUrl: "https://api.freebe.co.kr/" });
혹시 이렇게 공통으로 사용되는 URL은 상수화해서 가독성을 높이는 방법도 좋을 것 같은데, 상수화하는 것이 더 비용적으로 많이 들거나  특정한 경우에만 사용하는 패턴인지 이런 경우가 있다면 알려주면 좋을 것 같아!😊

2024-08-26 13:11 UTC, yuseok0215 commented on src/app/[id]/page.tsx
>    };
이 부분은 지금 더미 데이터로 담겨 있는데 추후 처리할 티켓이 따로 있는건가?? 아니라면 여기서 정리하는 것도 좋아보이는 데 확인 부탁해!

2024-08-26 13:11 UTC, yuseok0215 commented on src/services/server/photographer/mypage/products.ts
> +  }
catch 블록에서 error 변수가 선언되지 않은 것 같아! 확인 부탁해🫡

추가로 여기서도 콘솔로 에러 로그를 남기고 있는데 추가적인 에러 처리 로직에 대한 부분은 추가할 예정인지 아니면 추가를 안한 이유가 따로 있는지 궁금해!

2024-08-27 01:55 UTC, eujin-shin commented on src/services/client/core/index.ts
> +  }
아하 요 부분은 하단에 있는 beforeRetry에서 캐치하고 로그인 페이지로 리디렉션 시키고 있어!

beforeRetry: api 요청 실패했을 경우에 돌아가는 인터셉터, 만약 401 에러일 경우 토큰 재요청 함수를 호출하는 역할
refreshAccessToken: 실제로 토큰 재발급 api request를 보내는 역할

일단은 요렇게 구분되어 있는 상태!

2024-08-27 02:00 UTC, eujin-shin commented on src/services/client/core/index.ts
> +const clientApi = ky.create({ prefixUrl: "https://api.freebe.co.kr/" });
맞지 말해 준 대로 상수화하는 게 좋을 것 같아…! 환경변수도 정의했던 것 같은데 

1. 이번에 ngrok 링크를 임시로 걸다가 다시 원복할 때 깜박함
2. 배포 환경에서는 아직 환경변수가 제대로 세팅되지 않아서 요청을 못 보내게 됨

이 두 가지 이슈로 이렇게 되었던 듯 .. FU-155 토큰 관리하면서 인스턴스 생성 자체를 좀 손 볼 거라 그때 정리해 볼게! (티켓 요건에 작성했어 👍) 놓칠 뻔했는데 체크해 줘서 고마워 😂

2024-08-27 02:01 UTC, eujin-shin commented on src/app/[id]/page.tsx
>    };
이 부분은 이번 스프린트의 `FU-184 사진작가 프로필 조회` 티켓에서 api 호출 결과값으로 바뀔 예정입니닷! 👍

2024-08-27 02:29 UTC, eujin-shin commented on src/services/server/photographer/mypage/products.ts
> +  }
확인 고마워!! 추가했어 👍

이 부분은 좀 예외적인 상황이었는데, 원래 에러 핸들링 로직은 공통화해서 
1. http 인스턴스에서 에러 상태를 캐치
2. 공통된 에러 UI를 보여 줌

이렇게 처리되고 있었어! 그런데 이 부분의 경우 빌드 시도할 때 가장 외부의 페이지 컴포넌트가 정적 페이지로 미리 렌더링되는 과정에서 `데이터 페칭 함수에서 에러가 나서 배열 반환값이 돌아오지 않을 경우` 빌드 실패가 발생하는 바람에 .. 🤔 현재는 빌드 중 정적 페이지 생성 과정에서만 재현되는 에러로 이해하고 있고, 에러가 나도 무조건 빈 배열을 던져 줄 수 있도록 한 상태야!

`FU-158`에서 에러 핸들링 부분 다룰 때 특정 바운더리에 대해서만 핸들링하는 코드를 추가하려고 계획 중이라, 가능하다면 해당 파트 작업 중에 이 부분도 수정이 될 것 같긴 해!

2024-08-27 02:38 UTC, yuseok0215 commented on src/services/client/core/index.ts
> +const clientApi = ky.create({ prefixUrl: "https://api.freebe.co.kr/" });
자세한 설명 고마워! 
지금 CI/CD 배포 파이프라인 구축 중이니깐 마무리 될 때쯤 환경변수로 필요한 요소들 말해주면 같이 등록하는 방향으로 해보자!👍

2024-08-27 02:39 UTC, yuseok0215 commented on src/services/client/core/index.ts
> +  }
내가 놓친 부분이 있었네 ㅎㅎ.. 설명 고마워! 완전 이해됐어👍

2024-08-27 02:42 UTC, yuseok0215 commented on src/services/server/photographer/mypage/products.ts
> +  }
빌드 때문에 우회해서 처리한 건 좋은 것 같아!ㅎㅎ
따로 티켓에 작업 내역에 정리되어 있다면 TODO를 따로 쓸 필요도 없을 것 같고, FU-158 티켓에서 잘 처리해주면 깔끔하겠다! 
TODO 주석을 사용하는 걸 추천하려다가 후속 티켓에서 작업 요소들이 정리되어 있으면 주석을 꼭 쓸 필요는 없는 것 같아서 지금처럼 유지해도 좋을 것 같네😊

2024-08-27 02:43 UTC, yuseok0215 approved these changes

2024-08-27 02:47 UTC, merged