[FU-74] feat: add product create form
SWM-15th-ForU/freebe-frontend pull request #4
Opened 2024-07-24 12:44 UTC by eujin-shin

## 체크리스트

- [ ] 불필요한 주석 처리가 없는가?

## 작업 내역
* 상품 등록 폼 구현
* react-hook-form을 사용한 폼 상태 관리
* 조건부 입력을 포함한 상품 구성 / 옵션 / 할인 컴포넌트 추가

## 고민한 사항
* 보다 효율적인 입력 폼 상태 관리와, submit 시의 유효성 검증을 위해 react-hook-form을 도입하였습니다. 이 중 **복수의 이미지 등록, 배열 형태의 입력값 관리**에 고민이 있었습니다. 
* 이미지의 경우 입력 단계에서 최대 등록 개수를 제한할 수 없어 react-hook-form 내에 포함시키지 않고 별개의 상태로 분리하였고, 제출 시점에 나머지 입력값과 결합하여 api 요청에 포함시키는 방식을 사용하고자 합니다. 이 과정에서 추가로 드래그 & 드롭 이벤트를 핸들링 해 파일 추가를 가능하게 하는 방법을 확인하고 일부 반영하였으나, 시간을 많이 쓰기에는 우선순위가 낮은 부가 기능으로 여겨져 수정이 필요한 상태로 두게 되었습니다. 
* 또한 구성, 옵션, 할인 모두 배열의 형태이기 때문에, dynamic form 관리를 지원하는 useFieldArray를 사용해 구현하였습니다. 이 과정에서 `페이지 - 입력 폼 컴포넌트 - 배열 컴포넌트 - 배열 내 실제 입력 단위 컴포넌트`로 네 단계의 depth가 생겼습니다. 보통 예제에서는 배열 컴포넌트를 별도 구분하지 않고 입력 폼 컴포넌트 내부에서 작성하는 방식을 사용하고 있었으나 하나의 폼 안에 여러 개의 배열을 사용해야 하는 상황이라 컴포넌트를 한 단계 더 구분하게 되었고, 적절한 구분이었는지 고민이 있습니다.

## 리뷰 요청사항
* 커스텀 타입이 적절한지 검토해 주세요! (src/types/product-types.d.ts)
* 컴포넌트 간의 분리, 컴포넌트가 외부에서 받아오는 값인 props가 적절히 구성되었는지 살펴봐 주셔도 좋을 것 같습니다 😆

* 시급도 (낮음)
상품 등록 api 연결 외에 연결되어 있는 작업은 없습니다!

## 스크린샷
<img width="712" alt="스크린샷 2024-07-24 오후 9 42 09" src="https://github.com/user-attachments/assets/b1936532-9cff-47cd-b97f-dc9fd3192b73">

2024-07-25 12:42 UTC, yuseok0215 requested changes
스크린샷으로 올려준 것과 비교해서 코드를 보니깐 비교적 코드의 기능들이 눈에 더 잘 들어왔던 것 같아👍
그리고 이미지를 드래그 & 드롭과 같은 디테일한 파일 추가 기능을 추가해준 부분은 너무 좋아!!

2024-07-25 12:42 UTC, yuseok0215 commented on src/components/common/image-thumbnail.tsx
> +export default ImageThumbnail;
image-thumbnail.tsx에서 의도한 건 원본이미지를 상품 등록 페이지 내에서 작게 보여주기 위해 thumbnail 이미지로 리사징해서 보여주기 위해 만들어진거야?🤔

그리고 이미지 관련 tsx 파일이 common 폴더에 있는 이유도 궁금해!

2024-07-25 12:52 UTC, eujin-shin commented on src/components/common/image-thumbnail.tsx
> +export default ImageThumbnail;
맞아! 이후에 백엔드 쪽에서 리사이징된 url을 따로 넘겨준다고 하더라도 상품 등록 과정에서부터 업로드한 이미지를 썸네일 크기로 보여 주는 게 필요하긴 하더라구… 😂 

결국 화면 레이아웃에 따라 썸네일의 정확한 width, height가 유연하게 설정될 필요도 있을 것 같아서, '특정 이미지를 화면에서 필요한 크기로 보여 주는' 역할을 수행하는 컴포넌트로 생각하고 구현했고 다른 위치에서도 공통 사용될 여지가 있겠다고 생각되어서 common으로 넣어 두었어!

2024-07-26 03:02 UTC, rheeri commented on src/components/product/product-form.tsx
> +    items: [{ title: "기본 가격", content: "120,000원" }],
이건 상품 등록 들어갔을 때 기본으로 나타나는 컴포넌트인거지? 
예시 컴포넌트인데 120,000원은 왠지 너무 진짜 같기도 하고 ..?! 😂

2024-07-26 03:02 UTC, rheeri commented on src/components/product/item-input.tsx
> +        {...formRegister(`items.${index}.hasDescription`)}
체크박스를 선택했을때 상품 옵션에 대한 설명을 입력할 수 있게 되는거지?

와이어 프레임 그릴때는 컴포넌트 추가하면 설명란이 기본으로 표시되는걸 생각했었는데💭
상품 제목 하단에 **(선택) 상품 소개글을 입력해주세요.** 라고 보여지는 것 처럼!

디자이너님한테 공유한 자료에도 체크박스 언급은 별도로 없었어서 이 부분 한번 생각해봐줘 ㅎㅎ

2024-07-26 05:47 UTC, eujin-shin commented on src/components/product/item-input.tsx
> +        {...formRegister(`items.${index}.hasDescription`)}
요 부분은 와이어프레임 그릴 때 설명란 추가하는 기능을 어떤 형태로 넣을지 고민하다가 그냥 디자이너님한테 맡기는 게 낫겠다 싶어서 자세히 안 그려 놓고 각 컴포넌트가 '제목+설명+내용'이거나 '제목+내용'의 구조라고 요청해 두게 됐어…! 그래서 일단은 사용자가 선택할 경우에만 입력 받는다고 생각하고 선택 여부를 관리하는 데 임시로 체크박스를 쓰긴 했는데, 디자인 받고 거기 맞춰서 정리해 볼게!

2024-07-26 05:49 UTC, eujin-shin commented on src/components/product/product-form.tsx
> +    items: [{ title: "기본 가격", content: "120,000원" }],
응 맞아!! ㅋㅋㅋㅋ 듣고 보니까 가격 범위도 작가님마다 차이가 좀 있는데 금액까지 예시 값이 있는 건 좀 굳이 싶기도 하다… ㅎㅎㅎ 없애는 쪽으로 수정할게!

2024-07-26 06:12 UTC, rheeri commented on src/components/product/item-input.tsx
> +        {...formRegister(`items.${index}.hasDescription`)}
아아 오키오키👍 좋습니동~!

2024-07-26 06:21 UTC, rheeri approved these changes
이번 PR도 좋았다 🙆‍♀️

앗 커밋메시지에 피드백을 깜빡해서 덧붙이면,
어떤게 고민이었는지는 잘 모르겠지만 커밋 이력을 보다보니까 한글로 작성하면 좀 더 가독성이 좋겠다는 생각은 들었어!
(다른게 고민이었다면 더 얘기해줘  🙌)

2024-07-26 07:15 UTC, yuseok0215 approved these changes

2024-07-26 07:28 UTC, merged