Feat/fu 262 redirect
SWM-15th-ForU/freebe-frontend pull request #43
Opened 2024-10-04 08:56 UTC by eujin-shin

## 체크리스트

- [x] 불필요한 주석 처리가 없는가?

## 작업 내역
* 페이지 접근시 로그인 여부 및 사용자 권한에 따라 적절히 리다이렉트 되도록 로직 추가
`login` 및 `login/photographer`: 사진작가 로그인 상태일 경우 → photographer로 이동
`photographer/`: 사진작가 로그인 상태가 아닐 경우 → login/photographer로 이동
`customer/`: 로그인 상태가 아닐 경우 → login/customer로 이동
* 헤더 리다이렉트 개선 (로그인 상태 반영)
* 의뢰자측 로그인 페이지의 경우 리다이렉트 이전에 접근하려던 경로를 저장해 로그인 후 destination으로 사용
* 그외 로그인 페이지 UI 개선

## 고민한 사항
* 이전에 로그인 페이지에서 로그인 버튼이 첫 화면 범위 내에 보이지 않는 것에 대한 피드백이 있어서 반응형 UI를 조금 개선해 봤습니다! 아직 스크롤해야 버튼이 보이는 경우도 있긴 하지만… 🥲

## 리뷰 요청사항
* 로그인 한 이후에 헤더에서 로고를 클릭하면 `/photographer` 메인 페이지로 연결되게 처리했는데, 로그인 이전 화면에서 (작가측 로그인 or 의뢰자측 로그인 or 작가측 회원가입) 로고를 클릭했을 때 어디로 보낼지는 조금 애매해서 일단 링크를 뗀 상태입니다. 혹시 마땅한 페이지가 있다면 의견 부탁드려요! 연결해 놓겠습니다

* `src/components/buttons/login-button.tsx`: 공통 로그인 버튼
로그인 이후 리다이렉트 시킬 url을 받아 카카오 로그인 요청시 state로 보냅니다.
`src/app/login/redirect/route.ts`:
로그인 api 요청 이후 결과에 따라 사용자 role을 함께 저장하도록 수정했습니다.
`src/middleware.ts`:
matcher에 정의된 패턴과 일치하는 url로 요청이 발생할 경우 로그인 여부 및 사용자 권한을 체크하고 필요시 리다이렉트합니다.

## 스크린샷
<img width="1407" alt="스크린샷 2024-10-04 오후 5 48 46" src="https://github.com/user-attachments/assets/e5437e58-8a1d-4d6b-9233-d59fb8c408ff">
(* 아직 리다이렉트가 아니라 직접 의뢰자 로그인 페이지에 접근해 로그인할 경우, 로그인 이후에 보내 줄 만한 화면이 없어서 작가측 로그인 페이지에는 "의뢰자로 로그인하기" 링크를 걸지 않았습니다.)

2024-10-05 12:39 UTC, rheeri approved these changes
오 로그인 버튼 위치 옮겨진게 더 좋은 것 같기도 하고.! 피드백 잘 반영해줘서 고마워 🙇‍♀️ 로그인하기 전 화면에서 로고 클릭했을 때는 딱히 어디로 이동할 필요 없이 현재 페이지 그대로 머물게끔 하면 되지 않을까 싶어 ㅎㅎ 코드는 깔꼼하게 잘 정리되어 있는 것 같아서 별다른 피드백은 없습니당 ~!

2024-10-05 12:39 UTC, rheeri commented on src/middleware.ts
> +  ],
matcher에 이렇게 정의해두면 /photographer/join도 적절하게 처리되는지 궁금해!

2024-10-05 13:18 UTC, eujin-shin commented on src/middleware.ts
> +  ],
코멘트 보고 확인해 보니까 지금 코드로는 다른 `/photographer` 페이지랑 마찬가지로 로그인 & 사진작가 userRole이어야만 접근 가능하겠다…!! `/login/photographer`페이지랑 똑같이 처리되게 수정할게! 짚어줘서 고마워 👍

2024-10-07 02:19 UTC, yuseok0215 requested changes
카카오로 시작하기를 오른쪽에 배치하니깐 더 꽉차보여서 허전한 느낌이 많이 사라졌다!!👍👍
그리고 로그인 하기 전에 로고를 클릭했을 때는 사진의뢰자는 사진작가의 링크로 접속했으니깐 따로 페이지 이동이 없어도 될 것 같고, 사진작가도 로그인 페이지 이전에는 랜딩페이지 밖에 없어서 한번 회원가입을 한 상황이 대부분이니깐 따로 로고를 눌렀을 때 페이지 이동이 없어도 될 것 같아!

2024-10-07 02:19 UTC, yuseok0215 commented on src/middleware.ts
NextResponse.next()를 반환하는 코드가 중복되고 있어서 다른 반환 값 제외하고는 중복을 없애보면 어떨까?

그리고 로그인에 대한 유효성 검증을 진행할 때 사용하는 accessToken이나 roleType은 서버에서 응답하는 값을 중간에 가로채서 검증하는 과정이라고 이해하면 될까??

2024-10-07 02:56 UTC, eujin-shin commented on src/middleware.ts
accessToken / roleType 모두 요청에서 가로채는 거라고 봐 주면 될 것 같아! nextjs 서버로 요청이 들어오면 페이지가 렌더링 되기 전에 미들웨어가 실행되는 방식이라고 알고 있어. 얘기해 준 코드 중복은 한 번 리팩토링 해 볼게!! 고마워 👍

2024-10-07 03:12 UTC, yuseok0215 approved these changes

2024-10-07 06:21 UTC, merged