[FU-103] customer products page
SWM-15th-ForU/freebe-frontend pull request #7
Opened 2024-08-05 03:00 UTC by eujin-shin

## 체크리스트

- [x] 불필요한 주석 처리가 없는가?

## 작업 내역
* 의뢰자측 진입시 초기 화면 (`/{id}`)
* 상품별 상세 정보 페이지 (`/{id}/products/{productId}`)

## 고민한 사항
* **페이지 구분에 대해** 
상품별 페이지 내부에서 header가 공통으로 사용되는 점, 단 헤더 내부에서 현재 조회 중인 상품이 무엇인지 알 수 있어야 한다는 점을 고려하여 layout으로 처리하고 `usePathname`을 사용했습니다. 

* **css 작성 방식과 단위에 대해** 
초기에는 상대 단위 중 viewport를 기준으로 하는 `vw`, `vh`를 활용하고자 했습니다. 단 현재 모바일 너비를 기준으로 작업 중이며, 의뢰자 측 화면은 PC - 모바일 반응형으로 적용하기보다 PC 너비에서도 모바일 화면과 유사하게 너비를 제한하여 활용하는 것을 예상 중이기에 적합하지 않다고 느껴 절대 단위 + 부모 크기에 대한 상대 단위 `%`를 사용하는 방식으로 수정하였습니다.
또한 css import가 지나치게 많아질 경우 추후 수정에 불편함이 있을 것으로 우려되어 페이지 단위로 객체를 생성하고 각 스타일 객체를 그 안의 field로 넣는 방식을 시도하였습니다. (`product.css.ts`의 `iconStyle` 등)

## 리뷰 요청사항
현재는 페이지에 들어갈 예시 값을 변수로 정의하여 레이아웃을 확인 중이며, 이후 이 변수들에 api 호출 결과를 연결하는 방식으로 수정될 것 같습니다. 다음 api 호출 위치와 필드 위주로 확인해 주시면 좋을 것 같습니다! 🙇
* `src/app/[id]/page.tsx`에서 작가의 기본 정보 조회 (`photographerProfile`)
* `src/app/[id]/products/layout.tsx`에서 작가의 상품 목록 조회 (`products`)
* `src/app/[id]/products/[product]/page.tsx`에서 특정 상품의 상세 정보 조회 (`productData`)

## 스크린샷
<img width="235" alt="스크린샷 2024-08-05 오전 10 38 55" src="https://github.com/user-attachments/assets/9a355d3a-1925-4b92-b0cf-3db4335f02a9">
<img width="246" alt="스크린샷 2024-08-04 오후 2 52 05" src="https://github.com/user-attachments/assets/25b394d1-0ed6-47c0-9155-55b10b8c9c78">
<img width="246" alt="스크린샷 2024-08-04 오후 2 52 13" src="https://github.com/user-attachments/assets/5412df5c-a969-47eb-a60f-3929f62bb223">

2024-08-05 10:10 UTC, yuseok0215 requested changes

2024-08-05 10:10 UTC, yuseok0215 commented on src/app/[id]/products/[product]/page.tsx
> +  };
사소한 부분이기는 한데, 레이아웃 순서에 맞게 필드 순서를 작성해주면 더 가독성이 좋을 것 같기도 해!

2024-08-05 10:10 UTC, yuseok0215 commented on src/app/[id]/page.tsx
> +    { name: "자주 묻는 질문", src: "/faqs" },
이 부분은 추후에 만든 뒤에 링크 연결시켜 줄 부분으로 보여지는데, TODO 주석을 추가하면 다른 개발자가 해당 코드를 확인했을 때 헷갈리지 않을 것 같아!
하지만 추후 있을 작업에서 추가할 것이라는 게 명확하게 보여진다면 불필요하게 주석을 추가할 필요는 없을 것 같고! 한 번 고려만 해주면 좋을 것 같네😊

2024-08-05 10:10 UTC, yuseok0215 commented on src/app/[id]/page.tsx
> +      "6,7,8월 유료촬영 문의 받습니다! 🍀누구나 청춘 영화 속 주인공이 될 수 있어요 -!🥰언제 꺼내 봐도 웃음 나는 사진을 찍어 드릴게요 :-)",
혹시 이 부분 나중에 소개글이 너무 길어질 때 스마트폰 한 화면 내에서 안보이는 문제도 고려해서 최대 글자 수를 미리 지정해두는 게 좋을까?? 
만약 휴대폰마다 화면 편차가 있어서 어쩔 수 없이 스크롤을 내려하는 경우가 생긴다면 크게 문제가 되지는 않을 것 같지만, 어느정도 최대 글자 수를 제한해 두는게 좋을 것 같기도 해! 물론 내부적으로 논의를 해봐야 할 것 같고, 논의된 방향대로 서버에서도 검증을 진행할거야😄

2024-08-05 10:10 UTC, yuseok0215 commented on src/app/[id]/products/[product]/page.tsx
> +      </Carousel>
이미지 슬라이드를 보여주는 컴포넌트로 보여지는데,  Carousel.Slide에 내용이 없는 이유가 따로 있어? (추후에 개발 예정이라던지..!?)
내 생각에는 image 데이터를 활용해서 슬라이드를 렌더링 해줘야 할 것 같아서 물어봐💭

2024-08-05 10:10 UTC, yuseok0215 commented on src/app/[id]/products/layout.tsx
> +    </div>
overflowX: "hidden" 이 코드로 가로 스크롤은 가리는 건 이해가 됐는데, 혹시 오른쪽에 상품들을 더 보려면 이동해야 될 것 같은데 이 부분에 대해서 정의가 된건지 궁금해! (내가 코드를 잘 못봐서 어디인가에 정의해뒀을 수도 있어...😅)

2024-08-05 10:10 UTC, yuseok0215 commented on src/app/[id]/products/page.tsx
> +export default ProductViewPage;
이 부분은 어떤 역할을 해주는거야??🧐
PR에는 작가의 기본 정보 조회를 담당하는 것 같은데 코드가 없어서...! 설명해주면 너무 고마울 것 같아🥲

2024-08-05 10:10 UTC, yuseok0215 commented on src/containers/customer/main/info-sheet.tsx
> +};
이 부분에서 id가 따로 사용되고 있지 않은데 혹시 정의는 했지만 내부 로직에서 사용하지 않은 이유가 따로 있어??💭

2024-08-05 11:14 UTC, eujin-shin commented on src/app/[id]/products/[product]/page.tsx
> +  };
오 좋당 👍 수정했어!

2024-08-05 11:17 UTC, eujin-shin commented on src/app/[id]/page.tsx
> +    { name: "자주 묻는 질문", src: "/faqs" },
아하 이 부분은 각 페이지에 대한 path를 정해서 넣어 둔 거라 이 path에 해당하는 page를 추가로 구현할 예정이야! (지금 products/page.tsx 를 추가했듯이) path 자체를 변경하지 않는 이상 이 코드 자체에 대해서는 수정이 없을 것 같아서 이렇게 두게 되었어!!

2024-08-05 11:21 UTC, eujin-shin commented on src/app/[id]/page.tsx
> +      "6,7,8월 유료촬영 문의 받습니다! 🍀누구나 청춘 영화 속 주인공이 될 수 있어요 -!🥰언제 꺼내 봐도 웃음 나는 사진을 찍어 드릴게요 :-)",
오 좋은 생각이야!! 
사실 외부 링크 버튼 때문에 스크롤 자체가 없기는 힘들 것 같은데, 그 외에도 소개글이 너무 길어서 '상품 예약하기' 같은 버튼이 한 눈에 보이지 않는 걸 지양하기 위해 최대 글자수는 지정하는 쪽이 좋겠다! 
추가로 프론트 쪽에서 소개글 영역의 최대 높이를 제한해서, 소개글이 길어지더라도 기본 버튼까지는 한 눈에 들어오도록 조정하는 것도 좋을 것 같네!! 일단 TODO 주석 달아 뒀어 !

2024-08-05 11:23 UTC, eujin-shin commented on src/app/[id]/products/[product]/page.tsx
> +      </Carousel>
말해 준대로 image 데이터를 활용해야 하는 게 맞아! 그런데 지금은 유효한 uri 없이 임의의 문자열로 데이터를 만들어 둔 상태라 <Image> 태그에 넣어 주면 화면이 깨지는 관계로 … 🥲 요 부분은 api 연결과 함께 마무리될 것 같아 👍

2024-08-05 11:28 UTC, eujin-shin commented on src/app/[id]/products/layout.tsx
> +    </div>
이 부분은 `containers/product/product.css.ts`에 정의된 headerStyle에 포함되어 있어! 

(여긴 굳이 꼼꼼히 읽진 않아도 되는 css 얘기..) overflow는 자식 컴포넌트가 자신보다 클 때의 처리 방식을 결정하는데, 페이지 전체를 감싸고 있는 div에서는 overflowX: hidden을 넣지 않으면 페이지 자체가 좌우로 살짝 당겨지게 돼서 막아두고 헤더 영역에서부터 overflow를 허용해 뒀어!

2024-08-05 11:34 UTC, eujin-shin commented on src/app/[id]/products/page.tsx
> +export default ProductViewPage;
이 부분 같은 경우에는 스크린샷에 첨부한 두 페이지 (`/{id}`와  `/{id}/products/{productId}` )의 중간에 위치하는 페이지(`/{id}/products`)라고 생각해 주면 될 것 같아!

요 루트로 접근했을 때 404 페이지가 나오는 것보단 상품 상세 페이지의 헤더라도 확인하고, 그 중 하나의 상품을 선택해서 실제 상품 상세 정보 페이지로 이동할 수 있게 하는 게 더 좋을 것 같아서 일단 헤더 외의 영역은 비워두고서라도 하나 만들었어!

2024-08-05 11:39 UTC, eujin-shin commented on src/containers/customer/main/info-sheet.tsx
> +};
id는 페이지로부터 받아온 작가의 아이디인데, 여기서 '상품 예약' '스케줄 조회' '자주 묻는 질문'으로 넘어가는 버튼을 정의하고 있다 보니 각 페이지로 넘어갈 때 작가의 아이디를 넘겨 줘서 조회 api 호출에 사용하게 해야 할 수도 있을 것 같아서 일단 가지고 있게 했어!

사실 넘어간 각 페이지에서도 path에 접근해서 작가 아이디를 얻을 수는 있기 때문에 추후에 api 호출 구현하면서 없어질 수도 있는 부분이긴 해! 🤔

2024-08-06 02:01 UTC, yuseok0215 commented on src/app/[id]/page.tsx
> +    { name: "자주 묻는 질문", src: "/faqs" },
좋아좋아! 다시 봤을 때도 의도가 명확해보여서 굳이 주석을 넣을 필요는 없어 보이네!
피드백 고마워🤩

2024-08-06 02:02 UTC, yuseok0215 commented on src/app/[id]/page.tsx
> +      "6,7,8월 유료촬영 문의 받습니다! 🍀누구나 청춘 영화 속 주인공이 될 수 있어요 -!🥰언제 꺼내 봐도 웃음 나는 사진을 찍어 드릴게요 :-)",
좋아! 시급도가 높지는 않은 테스크이니깐 주석으로 잘 달아줬고, 이번 스프린트 끝쯤이나 다음 스프린트 시작할 때쯤 한번 언급해줘서 처리하면 좋을 것 같네👍

2024-08-06 02:05 UTC, yuseok0215 commented on src/app/[id]/products/[product]/page.tsx
> +      </Carousel>
그런 이슈가 있었구나..! 그러면 api 연결할 때 잊지 않고 해주면 좋을 것 같아!👍

2024-08-06 02:07 UTC, yuseok0215 commented on src/app/[id]/products/layout.tsx
> +    </div>
오.. 아냐 시간내서 작성해줘서 고맙고, 완전 도움 됐어😄 products의 경로를 한번 확인해봤어야 했는데 다음부터는 덕분에 잘 확인할 수 있을 것 같아!!

2024-08-06 02:10 UTC, yuseok0215 commented on src/app/[id]/products/page.tsx
> +export default ProductViewPage;
`/{id}/products` 이 루트로 접근했다는 건 사용자가 직접 URL을 수정해서 접근했을 때를 얘기하는건가??

2024-08-06 02:13 UTC, yuseok0215 commented on src/containers/customer/main/info-sheet.tsx
> +};
내 개인적인 생각으로는 첫 번째로 얘기했던 `각 페이지로 넘어갈 때 작가의 아이디를 넘겨 줘서 조회 api 호출에 사용` 이 방법을 사용하면 로딩 속도에서 조금 더 이점이 있을 것 같아 보여!
넘어간 각 페이지에서 path에 접근해서 작가 아이디를 캐치해서 두번 호출하면 조금 더 늦게 반환되는게 아닌가 해서! (이 부분은 유진이가 의도한 것과 다르게 해석한 것일 수도 있어서 한번 확인만 해주면 좋을 것 같아!😅)

2024-08-06 02:25 UTC, yuseok0215 approved these changes
PR에 설명을 꼼꼼하게 잘 작성해줘서 리뷰하는데 많은 도움이 됐습니다.👍

2024-08-06 02:25 UTC, eujin-shin commented on src/app/[id]/products/page.tsx
> +export default ProductViewPage;
그것 포함 약간의 예외 상황(현재 상품이 없다든지…!)이나, 메인 페이지에서 바로 상품 상세 페이지로 넘어가려면 어떤 한 상품의 아이디를 무조건 메인 페이지에서 가지고 있어야 해서 일단은 중간 단계로 이 페이지를 끼워 둔 상태야!

2024-08-06 02:26 UTC, eujin-shin commented on src/containers/customer/main/info-sheet.tsx
> +};
맞아! 나도 말해 준 대로 이미 상위에서 들고 있는 정보니까 새로 조회하는 것보단 넘겨 주는 게 더 좋을 것 같단 생각이 들었어! 성능이랑 구현 방식을 고려해서 나머지 작업 해 볼게 👍

2024-08-06 02:26 UTC, merged