[FU-333] UI enhancement
SWM-15th-ForU/freebe-frontend pull request #72
Opened 2024-10-31 07:46 UTC by eujin-shin

## 체크리스트

- [x] 불필요한 주석 처리가 없는가?

## 작업 내역
v1.1.0에서 발생한 UI 수정사항을 반영했습니다.

* 상품 관련
등록 / 수정 페이지: 소개글 입력란 나타나지 않는 현상 수정
목록 페이지: 삭제 / 비활성화시 모달을 통해 한 차례 확인
등록 페이지: 예시 상품 링크 연결, 해당 상품이 등록 가이드의 역할을 함께 수행할 수 있을 것으로 보여 디폴트 컴포넌트 중 보정본 수의 예시 설명 제거

* 고유 링크 접근 관련
사이드 메뉴의 '내 링크 복사' 항목을 수정

* 기타
모바일에서 튜토리얼 진행시 PC 환경에서 진행하도록 권장
의뢰자측 신청서 작성 시 상품 및 옵션에 대한 도움말 추가
지난 예약 페이지의 촬영 완료 일시 깨지는 현상 수정
서비스 링크 수정 (서비스 안내: 랜딩 페이지 / 공지사항: 슬래시 페이지 내 공지사항 / 고객센터: 카카오톡 채널홈)

## 고민한 사항
* 모바일 환경에서는 튜토리얼 진행이 어려울 것 같아서 (튜토리얼 단계별로 하이라이팅하는 요소가 한 화면 안에 나타나지 않음) '튜토리얼 보기' 버튼을 표시하지 않고 있었는데, 가입시에 자동으로 튜토리얼이 시작되었다 보니 모바일로 가입한 사용자들이 튜토리얼을 진행하면서 UI가 깨졌을 수 있겠다는 생각이 들었습니다 🥲 일단은 모바일에서도 튜토리얼이 동작하게 하려면 작업이 좀 많이 필요할 것 같고, 튜토리얼 확인 후 우선순위가 높은 '상품 등록', '프로필 설정' 등의 기능이 PC 환경에 최적화되어 있다는 점을 고려해서 아래와 같이 메시지를 띄워 주고 PC 환경에서 접속할 것을 권장하는 방향으로 수정해 두었습니다. 
<img width="488" alt="스크린샷 2024-10-31 오후 4 44 29" src="https://github.com/user-attachments/assets/8d3b7249-a9d5-43ee-8ccb-76d213a61333">

## 리뷰 요청사항
* 예시 상품은 아래 스크린샷과 같이 링크로 걸어두었는데, 텍스트나 표시 방식이 적절할지 검토 부탁드려요! (접근성이 좋게 배치하고 싶었는데, 또 서비스 이용 초기에만 보고 상품을 등록할 때마다 매번 확인하진 않을 것 같아서 고민이 됐습니다 😂)
<img width="815" alt="스크린샷 2024-10-31 오후 4 38 37" src="https://github.com/user-attachments/assets/5881ce61-af32-4a71-8155-8e66fb4f8756">

* 내 페이지 접근과 관련해 아래와 같이 팝업창을 추가하고, 여기서 바로 페이지로 이동하거나 링크를 복사할 수 있도록 추가했습니다. '내 예약 페이지'라고 설명하고 있는데 괜찮은지…! UI 상에서 수정할 만한 부분이 있다면 피드백 부탁드려요!
<img width="465" alt="스크린샷 2024-10-31 오후 4 39 04" src="https://github.com/user-attachments/assets/b718599a-4b30-4ee7-b616-f544b256d09a">

## 스크린샷
![스크린샷 2024-10-30 오후 5 43 51](https://github.com/user-attachments/assets/7e6f7f29-f1d5-452c-b72b-5426d62c7880)
![스크린샷 2024-10-30 오후 5 44 36](https://github.com/user-attachments/assets/2bc8e330-754d-45cf-9115-46e6220dac3c)

2024-10-31 10:38 UTC, rheeri requested changes
에궁 고생많았어 ㅜㅜ!! 속도 진짜 빠르당 💨
어제 멘토링 시간에 피드백 있었던 내용 대부분 반영해줘서 고마오 ㅎㅎ 

- `내 예약 페이지` 버튼에서 도움말이 "클립보드에 복사되었습니다.복사한 링크를 고객에게 전달해보세요!" 요건데, 다르게 수정해보면 어떨까? 
  > ex ) "링크를 복사해 인스타그램 프로필에 게시해보세요. 등록한 상품을 고객들이 구경할 수 있어요!"
</br>

- 지금 가입자 100%가 다 모바일인 상태에서 튜토리얼이 모바일에서 깨지게 된게 아쉽네 ㅜㅜ 우리 예상으론 PC 비율도 꽤 있을거라 생각했는데 100%라니.. 🤣 지금부터는 모바일 뷰를 최적화해보는 것도 좋을거같다..! 
  - 몬가 내 생각엔 튜토리얼을 PC버전에서 확인하라고 안내문구를 띄워줘도 실제로 PC를 켜서 확인해보는 사람은 거의 없을 거 같아.. 그래서 모바일 버전에서 사용 절차를 간단하게 이해시켜주는게 꼭 필요할 거 같은데, 가장 쉬운 방법으로는 사이드 메뉴에 넘버링을 해주는건 어떨까 싶어!! 
  (1). 촬영 상품 등록
  (2). 프로필 설정
  (3). 내 링크 복사
  이런식으로! 한번 생각해보고 의견 남겨줘!
<br>

- 내 예약 페이지를 구경할 수 있는 접근성을 좀 더 높여보면 좋을거같아! `바로가기` 버튼이 생겨서 좋은데👍 저 버튼을 안눌러보고 나가는 사람들도 꽤 있을거 같아서.. 좀 더 빠르게 접근할 수 있으면 어떨까싶어! 예를 들면 헤더에 고정적으로 배치하기..?

<br>

- `상품 등록`에서 예시보기 버튼이 더 눈에 띄었으면 좋겠어!! 지금 시점에서는 상품 등록이 무조건 이뤄져야 할거같아서 안예쁘더라도 상품 등록 페이지에 들어간 사람은 무조건 예시보기 버튼을 눌러볼만한 디자인이면 어떨까!!

2024-11-01 02:10 UTC, yuseok0215 reviewed
아무래도 UX 향상시켜야 되다보니 유진이가 작업해줘야 할 부분이 많았는데 디자인도 같이 병행하면서 작업을 빨리 해줘서 고마워👍 고생 많았어 ㅎㅎ

- 모바일 뷰에서 튜토리얼 관련해서 피드백은 스크린샷 찍어준 회원가입 시 뜨는 모달창에서 사이드바 메뉴에서 튜토리얼에서 권장하는 순서대로 표기해줘서(텍스트 형태로) 모바일에서도 직접 해볼 수 있게 하면 어떨까 싶어! ex) (1) 촬영 상품 등록 (2) 프로필 설정 (3) 내 예약 페이지 순으로 초기 설정을 진행해보세요!
- 상품 등록 페이지에서 '등록 예시 보기'도 지금은 상품 등록하신 분이 거의 없다 보니 좀 더 눈에 띄는 게 좋을 것 같아! 그리고 대부분의 사용자가 상품 등록이 된 시점에 스크린샷과 같이 연한 색으로 필요할 때만 볼 수 있게 하는 게 좋을 것 같구!
- 내 예약 페이지로 바뀌면서 기존의 튜토리얼도 함께 변경된건가?? (따로 스크린샷이 없어서 물어봐😄)

2024-11-01 08:51 UTC, eujin-shin commented
* 모바일 버전 튜토리얼
아예 기존 튜토리얼이랑 분리해서 넣어뒀어! 모바일뷰에는 모달이 좀 좁아지다 보니까 이전/다음 버튼 위치를 바꿨는데 그렇게 직관적이지는 않은 것 같아서… 🤔 혹시 의견 있다면 알려줘!
![FU-333](https://github.com/user-attachments/assets/2905b0f5-3697-4857-9280-de0bd8606bcf)

* 내 예약 페이지 안내
올려준 도움말은 팝업창에 추가했고, 복사 완료 메시지 조금 수정했어! 바로 가기를 좀 더 바깥쪽에 꺼내는 것도 고민해 봤는데 헤더에 넣기에는 요소가 좀 많아지는 것 같아서… 🥲
<img width="935" alt="스크린샷 2024-11-01 오후 4 42 04" src="https://github.com/user-attachments/assets/c3fb7b3f-5386-483d-aed6-21ff74f2ba58">

* 상품 등록 예시
페이지 처음 열리자마자 팝업으로 뜨게 변경했어! (아무데나 클릭하면 닫힘) 안내 문구가 좀 고민됐는데 아이디어 있으면 남겨줘!!
<img width="413" alt="스크린샷 2024-11-01 오후 4 31 42" src="https://github.com/user-attachments/assets/18107212-c451-468c-b093-7ae52253c7f4">

2024-11-02 05:18 UTC, yuseok0215 approved these changes
모바일 튜토리얼까지 빠르게 구현해줬었구나 ㅠㅠ 고생 많았어! 이걸 통해서 활성 사용자가 생기길 기다려보자👍👍👍

모바일 버전 튜토리얼은 각 단계를 다 설명해주고 있는 것 같아서 좋아! 첫번째 메인페이지 부분에서 튜토리얼을 통해서 우리 서비스가 pc환경에서 최적화라는 걸 확실하게 인지하기 어렵지 않을까..? 하는 생각이 들었고 그래서 튜토리얼 마지막에서도 "PC 환경에서 더 나은 서비스를 경험해보세요!" 처럼 텍스트를 추가해서 한번 더 강조를 해주면 좋을 것 같다는 생각이 있었어!

촬영 정보 등록하기 안내문구는 충분한 것 같아! 등록한 뒤에도 수정할 수 있다는 것도 인지시킬 수 있었고! 등록 예시 미리보기는 우리가 등록한 freebe_official의 예시 상품 상세 페이지로 이동하는거겠지??

2024-11-02 07:34 UTC, rheeri approved these changes
고생많았어 유진아 🥹💗

2024-11-02 07:58 UTC, eujin-shin commented
> 모바일 튜토리얼까지 빠르게 구현해줬었구나 ㅠㅠ 고생 많았어! 이걸 통해서 활성 사용자가 생기길 기다려보자👍👍👍
> 
> 모바일 버전 튜토리얼은 각 단계를 다 설명해주고 있는 것 같아서 좋아! 첫번째 메인페이지 부분에서 튜토리얼을 통해서 우리 서비스가 pc환경에서 최적화라는 걸 확실하게 인지하기 어렵지 않을까..? 하는 생각이 들었고 그래서 튜토리얼 마지막에서도 "PC 환경에서 더 나은 서비스를 경험해보세요!" 처럼 텍스트를 추가해서 한번 더 강조를 해주면 좋을 것 같다는 생각이 있었어!
> 
> 촬영 정보 등록하기 안내문구는 충분한 것 같아! 등록한 뒤에도 수정할 수 있다는 것도 인지시킬 수 있었고! 등록 예시 미리보기는 우리가 등록한 freebe_official의 예시 상품 상세 페이지로 이동하는거겠지??

모바일 튜토리얼 마지막 단계에 안내 문구 추가했어! 등록 예시 미리보기는 얘기한 대로 https://www.freebe.co.kr/freebe_official/products/8 여기로 이동해 🤓

2024-11-02 07:59 UTC, merged